#!/usr/bin/env python3
"""Shared Keynote native-effect identifiers used by archive analyzers."""

TRANSITION_EFFECTS = {
    "none",
    "apple:magic-move-implied-motion-path",
    "apple:ca-text-shimmer",
    "apple:ca-text-sparkle",
    "apple:ca-swing",
    "apple:ca-cube",
    "apple:ca-dissolve-and-flip",
    "apple:ca-pop",
    "apple:ca-push",
    "apple:ca-revolve",
    "apple:ca-zoom",
    "apple:ca-isometric",
    "apple:ClotheslinePush",
    "com.apple.iWork.Keynote.KLNConfetti",
    "apple:push",
    "apple:move in",
    "apple:dissolve",
    "apple:bounce",
    "apple:droplet",
    "com.apple.iWork.Keynote.BLTFadeThruColor",
    "apple:apple-grid",
    "apple:wipe-iris",
    "apple:slide",
    "apple:fade and move",
    "apple:fade-and-move",
    "apple:zoom",
    "apple:scale",
    "apple:reveal",
    "apple:wipe",
    "apple:FlipThrough",
    "com.apple.iWork.Keynote.BLTBlinds",
    "com.apple.iWork.Keynote.KLNColorPlanes",
    "apple:3D-cube",
    "apple:doorway",
    "apple:fall",
    "apple:revolve",
    "com.apple.iWork.Keynote.BUKFlop",
    "com.apple.iWork.Keynote.BLTMosaicFlip",
    "apple:pageflip",
    "apple:pivot",
    "com.apple.iWork.Keynote.BLTReflection",
    "com.apple.iWork.Keynote.BLTRevolvingDoor",
    "com.apple.iWork.Keynote.KLNSwap",
    "com.apple.iWork.Keynote.BLTSwoosh",
    "apple:twirl",
    "com.apple.iWork.Keynote.BUKTwist",
    "apple:radial wipe",
}
